const CONST = {
	PAIR_PRE_TYPE : 1,
	PAIR_SUFFIX_TYPE : 2,
	FOLD_PRE_TYPE : 1,
	FOLD_SUFFIX_TYPE : 2,
	MAX_FOLD_LINE: 10000,
	// 词语类型-BEGIN
	KEYWORD_TYPE: 1,
	LEFT_PARENTHESES: 2, //'('
	RIGHT_PARENTHESES: 3, //')'
	LEFT_SQUARE_BRACKETS: 4, //'['
	RIGHT_SQUARE_BRACKETS: 5, //']'
	LEFT_BRACES: 6, //'{'
	RIGHT_BRACES: 7, //'}'
	SINGLE_QUOTATION_TYPE: 9, //'''
	DOUBLE_QUOTATION_TYPE: 10, //'"'
	START_COMMENT_TYPE: 11, //'/*'
	END_COMMENT_TYPE: 12, //'*/'
	COMMENT_TYPE: 13, //'//'
	UNARY_OP_TYPE: 14, //单目运算符
	BINARY_OP_TYPE: 15, //双目运算符
	TERNARY_OP_TYPE: 16, //三目运算符
	CONSTANT_TYPE: 17, //常数
	IDENTIFIER_TYPE: 18, //标识符
	SEMICOLON_TYPE: 19, //';'
	RESULT_TYPE: 20, //表达式结果
	ESCAPE_TYPE: 21, //转义符
	// 词语类型-END

}
export default CONST